steps:
  - id: Build image
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=us.gcr.io/$PROJECT_ID/forecasting:$SHORT_SHA
      - --cache=true
      - --cache-ttl=12h
      - --context=.
      - --dockerfile=forecasting/Dockerfile

images:
  - us.gcr.io/$PROJECT_ID/forecasting:$SHORT_SHA

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHCPU_8
