steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/forecasting/tft:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/forecasting/tft:latest']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/forecasting/tft:latest'
