steps:
  - id: Build image
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:$SHORT_SHA
      - --destination=europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:latest
      - --context=forecasting
      - --dockerfile=Dockerfile
      - --cache=false
      - --cache-ttl=12h
      - --verbosity=info

images:
  - europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:$SHORT_SHA
  - europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY 

substitutions:
  _AR_REGION: europe-west1
  _AR_REPO: forecasting
  _IMAGE_NAME: tft
