steps:
  - id: Build image
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=europe-west1-docker.pkg.dev/tr-tech-dds-dev/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - --destination=europe-west1-docker.pkg.dev/tr-tech-dds-dev/${_AR_REPO}/${_IMAGE_NAME}:latest
      - --context=.
      - --dockerfile=forecasting/Dockerfile
      - --cache=true
      - --cache-ttl=12h

images:
  - europe-west1-docker.pkg.dev/tr-tech-dds-dev/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
  - europe-west1-docker.pkg.dev/tr-tech-dds-dev/${_AR_REPO}/${_IMAGE_NAME}:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHCPU_8

substitutions:
  _AR_REGION: europe-west1
  _AR_REPO: forecasting        # make sure this AR repo exists in europe-west1
  _IMAGE_NAME: tft
