steps:
  - id: Build image
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:$SHORT_SHA
      - --destination=europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:latest
      - --context=forecasting         # Context points to folder containing Dockerfile + requirements.txt
      - --dockerfile=Dockerfile       # Dockerfile inside forecasting/
      - --cache=true
      - --cache-ttl=12h

images:
  - europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:$SHORT_SHA
  - europe-west1-docker.pkg.dev/tr-tech-dds-dev/forecasting/tft:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHMEM_16

substitutions:
  _AR_REGION: europe-west1
  _AR_REPO: forecasting
  _IMAGE_NAME: tft
